package gui;

import Gerenciadores.GerenciadorMedicos;
import classes.Medico;
import java.io.FileNotFoundException;

public class DlgCadMedico extends javax.swing.JDialog {

    private boolean editando;
    private String cpfEscolhido;
    private Medico pessoaEditando;
    private GerenciadorMedicos gerenciadorMedicos;

    public DlgCadMedico(java.awt.Frame parent, boolean modal) throws FileNotFoundException {
        super(parent, modal);
        initComponents();

        this.gerenciadorMedicos = new GerenciadorMedicos();
        this.pessoaEditando = new Medico();
        this.editando = false;
        this.cpfEscolhido = "";
        
        this.gerenciadorMedicos = new GerenciadorMedicos();
        this.habilitarCampos(true);
        this.limparCampos();
        gerenciadorMedicos.carregarDoArquivo("ListagemMedicos.xml");
        String listagem = this.gerenciadorMedicos.toString();
        txtMedCads.setText(listagem);
    }


    public void habilitarCampos(boolean flag) {
        txtNomeMed.setEnabled(flag);
        txtHorarioL.setEnabled(flag);
        txtEspecialidade.setEnabled(flag);
        txtCRMcad.setEnabled(flag);
    }

    public void limparCampos() {
        txtNomeMed.setText("");
        txtHorarioL.setText("");
        txtEspecialidade.setText("");
        txtCRMcad.setText("");
    }

    public void objetoParaCampos(Medico m) {
        txtNomeMed.setText(m.getNome());
        txtHorarioL.setText(m.getHorariosDisponiveis() + "");
        txtEspecialidade.setText(m.getEspecialidade() + "");
        txtCRMcad.setText(m.getCrm());
    }

    public Medico camposParaObjeto() {
        Medico m = new Medico();

        m.setNome(txtNomeMed.getText());

        m.setHorariosDisponiveis(txtHorarioL.getText());

        m.setEspecialidade(txtEspecialidade.getText());

        m.setCrm(txtCRMcad.getText());

        return m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeMed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEspecialidade = new javax.swing.JTextField();
        txtHorarioL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCRMcad = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMedCads = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnCadMed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                formHierarchyChanged(evt);
            }
        });

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        txtNomeMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMedActionPerformed(evt);
            }
        });
        jPanel3.add(txtNomeMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 130, -1));

        jLabel3.setText("Especialidade");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, 10));

        txtEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadeActionPerformed(evt);
            }
        });
        jPanel3.add(txtEspecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 120, -1));

        txtHorarioL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorarioLActionPerformed(evt);
            }
        });
        jPanel3.add(txtHorarioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 130, -1));

        jLabel4.setText("Horarios Livres");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 10));

        jLabel2.setText("CRM");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 14, -1, -1));

        txtCRMcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCRMcadActionPerformed(evt);
            }
        });
        jPanel3.add(txtCRMcad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 180, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Cadastro de medico");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtMedCads.setColumns(20);
        txtMedCads.setRows(5);
        jScrollPane1.setViewportView(txtMedCads);

        btnCadMed.setText("Cadastrar");
        btnCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadMed)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadMed)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formHierarchyChanged

    private void txtHorarioLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorarioLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorarioLActionPerformed

    private void txtEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadeActionPerformed

    private void txtCRMcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCRMcadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCRMcadActionPerformed

    private void txtNomeMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMedActionPerformed

    private void btnCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMedActionPerformed
        Medico novoMedico = this.camposParaObjeto();

        if (this.editando) {
            this.gerenciadorMedicos.atualizarMedico(cpfEscolhido, novoMedico);
        } else { //Estou inserindo
            this.gerenciadorMedicos.addMedico(novoMedico);
        }

        this.limparCampos();
        this.habilitarCampos(false);

        String listagem = gerenciadorMedicos.toString();
        txtMedCads.setText(listagem);

        this.gerenciadorMedicos.salvarNoArquivo("ListagemMedicos.xml");
    }//GEN-LAST:event_btnCadMedActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCRMcad;
    private javax.swing.JTextField txtEspecialidade;
    private javax.swing.JTextField txtHorarioL;
    private javax.swing.JTextArea txtMedCads;
    private javax.swing.JTextField txtNomeMed;
    // End of variables declaration//GEN-END:variables
}
