/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import Gerenciadores.GerenciadorPacientes;
import classes.Paciente;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author igorxf
 */
public class DlgSelecionarPaciente extends javax.swing.JDialog {

    private boolean editando;
    private String codAntigo;
    private GerenciadorPacientes gerenciadorPaciente;
    
    public DlgSelecionarPaciente(java.awt.Frame parent, boolean modal) throws FileNotFoundException {
        super(parent, modal);
        initComponents();
        this.editando = false;
        this.codAntigo = "";
        this.gerenciadorPaciente = new GerenciadorPacientes();
        this.limparCampos();
        this.habilitarCampos(true);
        txtMedicosSelect.setEditable(false);
        
        gerenciadorPaciente.carregarDoArquivo("ListagemPacientes.xml");
        txtMedicosSelect.setText(gerenciadorPaciente.toString());
    }


    public void habilitarCampos(boolean flag) {
        txtCPFSelect.setEnabled(flag);
    }

    public void limparCampos() {
         txtCPFSelect.setText("");
    }

    public void objetoParaCampos(Paciente a) {
         txtCPFSelect.setText(a.getCpf());
    }

    public Paciente camposParaObjeto() {
        Paciente a = new Paciente();
        a.setCpf(txtCPFSelect.getText());
        
        return a;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        txtCPFSelect = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMedicosSelect = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnSelectPaciente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCpf.setText("CPF:");
        jPanel1.add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 10, -1, -1));

        txtCPFSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFSelectActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPFSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 5, 150, -1));

        txtMedicosSelect.setColumns(20);
        txtMedicosSelect.setRows(5);
        jScrollPane1.setViewportView(txtMedicosSelect);

        btnSelectPaciente.setText("Selecionar");
        btnSelectPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelectPaciente)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(btnSelectPaciente)
                .addGap(21, 21, 21))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Seleciona Paciente");
        jPanel3.add(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPacienteActionPerformed
         Paciente p = this.camposParaObjeto();

        if(this.editando){
            gerenciadorPaciente.atualizarPaciente(codAntigo, p);
        }else{
            gerenciadorPaciente.addPaciente(p);
        }

        
        //No final reset a tela
        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;

        String listagem = gerenciadorPaciente.toString();
        txtMedicosSelect.setText(listagem);
        
        try {
            gerenciadorPaciente.salvarNoArquivo("ListagemPacientes.xml");
        } catch (IOException ex) {
            Logger.getLogger(DlgCadConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.habilitarCampos(true);
    }//GEN-LAST:event_btnSelectPacienteActionPerformed

    private void txtCPFSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFSelectActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JTextField txtCPFSelect;
    private javax.swing.JTextArea txtMedicosSelect;
    // End of variables declaration//GEN-END:variables
}
