/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author igorxf
 */
public class FrHome extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public FrHome() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bntCadMed = new javax.swing.JButton();
        btncadPaciente = new javax.swing.JButton();
        btnAgendarConsulta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntCadMed.setText("Cadastro  Medicos");
        bntCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadMedActionPerformed(evt);
            }
        });
        jPanel1.add(bntCadMed);

        btncadPaciente.setText("Cadastro de Pacientes");
        btncadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(btncadPaciente);

        btnAgendarConsulta.setText("Agendar Consultas");
        btnAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgendarConsulta);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Sistema de Consultas");
        jPanel2.add(lblTitulo);

        javax.swing.GroupLayout penLayout = new javax.swing.GroupLayout(pen);
        pen.setLayout(penLayout);
        penLayout.setHorizontalGroup(
            penLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, penLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        penLayout.setVerticalGroup(
            penLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadMedActionPerformed

        try {
            DlgCadMedico cadMedico = new DlgCadMedico(this, true);
            cadMedico.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrHome.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_bntCadMedActionPerformed

    private void btnAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarConsultaActionPerformed

        try {
            DlgCadConsulta cadConsulta = new DlgCadConsulta(this, true);
            cadConsulta.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgendarConsultaActionPerformed

    private void btncadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadPacienteActionPerformed

        try {
            DlgCadPaciente cadPaciente = new DlgCadPaciente(this, true);
            cadPaciente.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncadPacienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadMed;
    private javax.swing.JButton btnAgendarConsulta;
    private javax.swing.JButton btncadPaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pen;
    // End of variables declaration//GEN-END:variables
}
