/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.projescolamvc.view;


import com.mycompany.projescolamvc.connection.SQLiteConnector;
import com.mycompany.projescolamvc.controller.DisciplinaController;
import com.mycompany.projescolamvc.view.tablemodels.TMCadDisciplina;
import com.mycompany.projescolamvc.model.dao.DisciplinaDAOBanco;
import com.mycompany.projescolamvc.model.dao.DisciplinaDAOFile;
import com.mycompany.projescolamvc.model.dao.IDao;
import com.mycompany.projescolamvc.model.entities.Disciplina;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author  igorxf
 */
public class JDialogDisciplina extends javax.swing.JDialog {
    
    private boolean editando;
    private String codAntigo;
    private DisciplinaController disciplinaController;
    

     public JDialogDisciplina(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
         this.editando = false;
         this.codAntigo = "";
         
        //IDao disciplinaDao = new DisciplinaDAOFile("ListagemDisciplinas.json");
        
        SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
        IDao disciplinaDao = new DisciplinaDAOBanco(conexao.getConnection());
        this.disciplinaController = new DisciplinaController(disciplinaDao);
         
        initComponents();
        setLocationRelativeTo(parent);
        

        this.habilitarCampos(false);
        this.limparCampos();
        this.atualizarTabela();
    }
    public void habilitarCampos(boolean flag) {
        edtCod.setEnabled(flag);
        edtNome.setEnabled(flag);
        edtSemestre.setEnabled(flag);
        edtHorario.setEnabled(flag);
    }

    public void limparCampos() {
        edtCod.setText("");
        edtNome.setText("");
        edtSemestre.setText("");
        edtHorario.setText("");
    }

    public void objetoParaCampos(Disciplina p) {
      edtCod.setText(p.getCod());
       edtNome.setText(p.getNome());
       edtSemestre.setText(p.getSemestre()+ "");
       edtHorario.setText(p.getHorario());
    }



    /**
     * Creates new form JDialogDisciplina
     */
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelDisciplina = new javax.swing.JPanel();
        jlbDisciplina = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEdt = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnMatricular2 = new javax.swing.JButton();
        btnMatricular = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblSemestre = new javax.swing.JLabel();
        edtSemestre = new javax.swing.JTextField();
        lblHorario = new javax.swing.JLabel();
        edtHorario = new javax.swing.JTextField();
        edtCod = new javax.swing.JTextField();
        lblCod = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grdDisciplina = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPanelDisciplina.setBackground(new java.awt.Color(153, 153, 153));

        jlbDisciplina.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlbDisciplina.setForeground(new java.awt.Color(0, 0, 0));
        jlbDisciplina.setText("Disciplina ");
        JPanelDisciplina.add(jlbDisciplina);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btnNovo.setBackground(new java.awt.Color(204, 204, 204));
        btnNovo.setForeground(new java.awt.Color(0, 0, 0));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNovo);

        btnEdt.setBackground(new java.awt.Color(204, 204, 204));
        btnEdt.setForeground(new java.awt.Color(0, 0, 0));
        btnEdt.setText("Editar");
        btnEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdtActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdt);

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);

        btnExcluir.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluir.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btnExcluir);

        btnSalvar.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);

        btnMatricular2.setBackground(new java.awt.Color(204, 204, 204));
        btnMatricular2.setForeground(new java.awt.Color(0, 0, 0));
        btnMatricular2.setText("Professor Ministrante");
        btnMatricular2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricular2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnMatricular2);

        btnMatricular.setBackground(new java.awt.Color(204, 204, 204));
        btnMatricular.setForeground(new java.awt.Color(0, 0, 0));
        btnMatricular.setText("Matricular Aluno");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });
        jPanel2.add(btnMatricular);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome");

        edtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeActionPerformed(evt);
            }
        });

        lblSemestre.setForeground(new java.awt.Color(0, 0, 0));
        lblSemestre.setText("Semestre");

        lblHorario.setForeground(new java.awt.Color(0, 0, 0));
        lblHorario.setText("Horario");

        edtHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtHorarioActionPerformed(evt);
            }
        });

        edtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodActionPerformed(evt);
            }
        });

        lblCod.setForeground(new java.awt.Color(0, 0, 0));
        lblCod.setText("Cod");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSemestre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemestre)
                    .addComponent(edtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorario)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(edtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCod))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        grdDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(grdDisciplina);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (this.editando == true) {
            this.disciplinaController.atualizarDisciplina(codAntigo, edtNome.getText(), edtSemestre.getText(), edtHorario.getText());
        } else {
            this.disciplinaController.adicionarDisciplina(edtCod.getText(), edtNome.getText(), edtSemestre.getText(), edtHorario.getText());
        }

        this.limparCampos();
        this.habilitarCampos(false);

        this.atualizarTabela();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
      this.limparCampos();
      this.habilitarCampos(true);
      this.editando = false;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Disciplina disciplinaEscolhida = this.getObjetoSelecionadoNaGrid();
        
        String nomeEscolhido = disciplinaEscolhida.getCod();
        
        Disciplina a = disciplinaController.buscarDisciplina(nomeEscolhido);

        if (a == null) {
            JOptionPane.showMessageDialog(this, "Não existe disciplina com este cod.");
        } else {
            this.disciplinaController.removerDisciplina(nomeEscolhido);
            JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
        }

        this.atualizarTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void edtHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtHorarioActionPerformed

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdtActionPerformed
        Disciplina disciplinaEscolhida = this.getObjetoSelecionadoNaGrid();
       
       String codEscolhido = disciplinaEscolhida.getCod();

        Disciplina disciplinaEditando = disciplinaController.buscarDisciplina(codEscolhido);

        if (disciplinaEditando == null) {
            JOptionPane.showMessageDialog(this, "Disciplina não existente na escola.");
            this.editando = false;
        } else {
            this.limparCampos();
            this.habilitarCampos(true);
            
            this.objetoParaCampos(disciplinaEditando);
            this.editando = true;
            this.codAntigo = disciplinaEditando.getCod();
        }
    }//GEN-LAST:event_btnEdtActionPerformed

    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
            String codEscolhido = JOptionPane.showInputDialog("Informe o nome da disciplina que deseja matricular o aluno", "");
            Disciplina DisciplinaEscolhida = disciplinaController.buscarDisciplina(codEscolhido);
            if(DisciplinaEscolhida== null){
                 JOptionPane.showMessageDialog(this, "Disciplina não existente na escola.");
            }else {
            JDialogSelectAluno tela = null;
                try {
                    tela = new JDialogSelectAluno(this,true, DisciplinaEscolhida);
                } catch (SQLException ex) {
                    Logger.getLogger(JDialogDisciplina.class.getName()).log(Level.SEVERE, null, ex);
                }
            tela.setVisible(true);
            atualizarTabela();
            }
    }//GEN-LAST:event_btnMatricularActionPerformed

    private void btnMatricular2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricular2ActionPerformed
            String codEscolhido = JOptionPane.showInputDialog("Informe o cod da disciplina que deseja adicionar o Professor Ministrante", "");
            Disciplina DisciplinaEscolhida = disciplinaController.buscarDisciplina(codEscolhido);
            if(DisciplinaEscolhida== null){
                 JOptionPane.showMessageDialog(this, "Disciplina não existente na escola.");
            }else {
            JDialogSelectProfessor tela = null;
                try {
                    tela = new JDialogSelectProfessor(this,true, DisciplinaEscolhida);
                } catch (SQLException ex) {
                    Logger.getLogger(JDialogDisciplina.class.getName()).log(Level.SEVERE, null, ex);
                }
            tela.setVisible(true);
            atualizarTabela();
            }
        
    }//GEN-LAST:event_btnMatricular2ActionPerformed

    private void edtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodActionPerformed
    
    private void grdAlunoMouseClicked(java.awt.event.MouseEvent evt) {                                       
       Disciplina a = this.getObjetoSelecionadoNaGrid();
       this.objetoParaCampos(a);
    }
    
    public Disciplina getObjetoSelecionadoNaGrid() {
        int linhaSelecionada = grdDisciplina.getSelectedRow();

        if (linhaSelecionada >= 0) {
            TMCadDisciplina tmCadAluno = (TMCadDisciplina) grdDisciplina.getModel();

             Disciplina d = tmCadAluno.getObjetoAluno(linhaSelecionada);
            return d;
        }
        
        return null;
    }
    
    public void atualizarTabela() {
        List<Disciplina> lista = this.disciplinaController.listarDisciplinas();
        TMCadDisciplina tmcadisciplina = new TMCadDisciplina(lista);
        grdDisciplina.setModel(tmcadisciplina);
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelDisciplina;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEdt;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMatricular;
    private javax.swing.JButton btnMatricular2;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCod;
    private javax.swing.JTextField edtHorario;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtSemestre;
    private javax.swing.JTable grdDisciplina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbDisciplina;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSemestre;
    // End of variables declaration//GEN-END:variables
}
