package com.mycompany.projescolamvc.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author  igorxf
 */
public class JFrameDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEscola
     */
    public JFrameDepartamento() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        lblEscola = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAluno = new javax.swing.JButton();
        btnProf = new javax.swing.JButton();
        btnDisciplina = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblEscola1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblEscola2 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        lblEscola.setBackground(new java.awt.Color(0, 102, 51));
        lblEscola.setFont(new java.awt.Font("Sylfaen", 0, 48)); // NOI18N
        lblEscola.setForeground(new java.awt.Color(255, 255, 255));
        lblEscola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscola.setText("Departamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEscola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEscola)
                .addGap(87, 87, 87))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnAluno.setBackground(new java.awt.Color(0, 102, 102));
        btnAluno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnAluno.setText("Aluno");
        btnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAluno, new java.awt.GridBagConstraints());

        btnProf.setBackground(new java.awt.Color(0, 102, 102));
        btnProf.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnProf.setForeground(new java.awt.Color(255, 255, 255));
        btnProf.setText("Professor");
        btnProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfActionPerformed(evt);
            }
        });
        jPanel2.add(btnProf, new java.awt.GridBagConstraints());

        btnDisciplina.setBackground(new java.awt.Color(0, 102, 102));
        btnDisciplina.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        btnDisciplina.setText("Disciplina");
        btnDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisciplinaActionPerformed(evt);
            }
        });
        jPanel2.add(btnDisciplina, new java.awt.GridBagConstraints());

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));

        lblEscola1.setBackground(new java.awt.Color(0, 102, 102));
        lblEscola1.setFont(new java.awt.Font("Sylfaen", 0, 36)); // NOI18N
        lblEscola1.setForeground(new java.awt.Color(255, 255, 255));
        lblEscola1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscola1.setText("Cadastro de Alunos, Professores e Disciplinas.");
        jPanel3.add(lblEscola1);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setToolTipText("");
        jPanel4.setLayout(new java.awt.GridBagLayout());

        lblEscola2.setBackground(new java.awt.Color(0, 102, 102));
        lblEscola2.setFont(new java.awt.Font("Sylfaen", 0, 48)); // NOI18N
        lblEscola2.setForeground(new java.awt.Color(255, 255, 255));
        lblEscola2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscola2.setText("Bem-vindo!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.ipady = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 100, 31, 120);
        jPanel4.add(lblEscola2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfActionPerformed

        JDialogProfessor tela = null;
        try {
            tela = new JDialogProfessor(this, true);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameDepartamento.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
    }//GEN-LAST:event_btnProfActionPerformed

    private void btnDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinaActionPerformed
       JDialogDisciplina tela = null;
        try {
            tela = new JDialogDisciplina(this, true);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameDepartamento.class.getName()).log(Level.SEVERE, null, ex);
        }
       tela.setVisible(true);
    }//GEN-LAST:event_btnDisciplinaActionPerformed

    private void btnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunoActionPerformed
       JDialogAluno tela = null;
        try {
            tela = new JDialogAluno(this,true);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameDepartamento.class.getName()).log(Level.SEVERE, null, ex);
        }
       tela.setVisible(true);
    }//GEN-LAST:event_btnAlunoActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAluno;
    private javax.swing.JButton btnDisciplina;
    private javax.swing.JButton btnProf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblEscola;
    private javax.swing.JLabel lblEscola1;
    private javax.swing.JLabel lblEscola2;
    // End of variables declaration//GEN-END:variables
}
